/*Q1*/
create table USER16.YELP_BUSINESS_P (pk VARCHAR PRIMARY KEY, BASE.NAME VARCHAR, BASE.STATE VARCHAR, BASE.STARS VARCHAR, BASE.ISOPEN INT)
as select "HBASE_ROW_KEY", BASE.NAME, BASE.STATE, BASE.STARS, "BASE.IS_OPEN" from "USER16.YELP_BUSINESS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index BIDX on "USER16.YELP_BUSINESS_P" (BASE.NAME, BASE.STATE, BASE.STARS, BASE.ISOPEN);

select BASE.NAME, BASE.STATE, BASE.STARS
from "USER16.YELP_BUSINESS_P"
where BASE.ISOPEN = 1
limit 1000;

drop table USER16.YELP_BUSINESS_P;


/*Q2*/
create table USER16.YELP_BUSINESS_P (pk VARCHAR PRIMARY KEY, BASE.NAME VARCHAR, BASE.ADRRESS VARCHAR, BASE.CITY VARCHAR, BASE.REVIEW_COUNT INT, BASE.CATEGORIES VARCHAR)
as select "HBASE_ROW_KEY", BASE.NAME, BASE.ADRRESS, BASE.CITY, "BASE.REVIEW_COUNT",BASE.CATEGORIES from "USER16.YELP_BUSINESS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index BIDX on "USER16.YELP_BUSINESS_P" (BASE.NAME, BASE.ADRRESS, BASE.CITY, "BASE.REVIEW_COUNT",BASE.CATEGORIES);

select BASE.NAME, BASE.CITY, BASE.ADDRESS, BASE.REVIEW_COUNT
from "USER16.YELP_BUSINESS_P"
where BASE.CATEGORIES = 'Drugstores'
order by BASE.REVIEW_COUNT DESC

drop table USER16.YELP_BUSINESS_P;


/*Q3*/
create table USER16_YELP_BUSINESS_P (pk VARCHAR PRIMARY KEY, BASE.REVIEWCOUNT FLOAT, BASE.ISOPEN INT, BASE.CATEGORIES VARCHAR, HOURS.MONDAY VARCHAR, HOURS.TUESDAY VARCHAR, HOURS.WEDNESDAY VARCHAR, HOURS.THURSDAY VARCHAR, HOURS.FRINDAY VARCHAR, HOURS.SATURDAY VARCHAR, HOURS.SUNDAY VARCHAR) 
as select "HBASE_ROW_KEY", BASE.REVIEWCOUNT, "BASE.IS_OPEN", BASE.CATEGORIES, HOURS.MONDAY, HOURS.TUESDAY, HOURS.WEDNESDAY, HOURS.THURSDAY, HOURS.FRINDAY, HOURS.SATURDAY, HOURS.SUNDAY from "USER16.YELP_BUSINESS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index BIDX on "USER16_YELP_BUSINESS_P" (BASE.REVIEWCOUNT, BASE.ISOPEN, BASE.CATEGORIES, HOURS.MONDAY, HOURS.TUESDAY, HOURS.WEDNESDAY, HOURS.THURSDAY, HOURS.FRINDAY, HOURS.SATURDAY, HOURS.SUNDAY);

select SUM(BASE.REVIEWCOUNT) as review count
from "USER16.YELP_BUSINESS_P"
where BASE.ISOPEN = 1 AND HOURS.MONDAY = '0:0-0:0' AND HOURS.TUESDAY = '0:0-0:0' AND HOURS.WEDNESDAY = '0:0-0:0' AND HOURS.THURSDAY = '0:0-0:0' AND HOURS.FRIDAY = '0:0-0:0' AND HOURS.SATURDAY = '0:0-0:0' AND HOURS.SUNDAY = '0:0-0:0'
group by BASE.CATEGORIES;

drop table USER16_YELP_BUSINESS_P;


/*Q4*/
create table USER16.YELP_BUSINESS_P (pk VARCHAR PRIMARY KEY, BASE.STATE VARCHAR, ATTRIBUTE.SMOKING INT,HOURS.SUNDAY VARCHAR )
as select "HBASE_ROW_KEY", BASE.NAME, BASE.STATE, ATTRIBUTE.SMOKING, HOURS.SUDNAY  from "USER16.YELP_BUSINESS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index BIDX on "USER16.YELP_BUSINESS_P" (BASE.STATE, BASE.SMOKING, ATTRIBUTE.SMOKING, HOURS.SUNDAY);

select BASE.STATE, COUNT(*)
from "USER16.YELP_BUSINESS_P"
where ATTRIBUTES.SMOKING =0 AND NOT HOURS.SUNDAY = 'None'
group by BASE.STATE

drop table USER16.YELP_BUSINESS_P;


/*Q5*/
create table CHECKINS_TABLE (pk VARCHAR PRIMARY KEY, PERHOUR.CHECKINS INT, PERHOUR.WEEKDAY VARCHAR, PERHOUR.HOUR TIME) as select "HBASE_ROW_KEY", PERHOUR.CHECKINS, PERHOUR.WEEKDAY, PERHOUR.HOUR from "USER16.YELP_CHECKIN" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index CIDX on "CHECKINS_TABLE"(PERHOUR.CHECKINS, PERHOUR.WEEKDAY, PERHOUR.HOUR);

select PERHOUR.WEEKDAY, PERHOUR.HOUR, COUNT(PERHOUR.CHECKINS)
from "CHECKINS_TABLE" 
group by PERHOUR.WEEKDAY, PERHOUR.HOUR;

drop table "CHECKINS_TABLE";


/*Q6*/
create table BUSINESSES (pk VARCHAR PRIMARY KEY, BASE.ISOPEN INT, BASE.CATEGORIES VARCHAR) as select "HBASE_ROW_KEY", BASE.ISOPEN, BASE.CATEGORIES from "USER16.YELP_BUSINESS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create table CHECKINS_TABLE (pk VARCHAR PRIMARY KEY, PERHOUR.CHECKINS INT, PERHOUR.BUSINESSID VARCHAR, PERHOUR.WEEKDAY VARCHAR, PERHOUR.HOUR TIME) as select "HBASE_ROW_KEY", PERHOUR.CHECKINS, PERHOUR.BUSINESSID, PERHOUR.WEEKDAY, PERHOUR.HOUR from "USER16.YELP_CHECKIN" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index BIDX on BUSINESSES(BASE.ISOPEN, BASE.CATEGORIES);

create index CIDX on "CHECKINS_TABLE"(PERHOUR.CHECKINS, PERHOUR.BUSINESSID, PERHOUR.WEEKDAY, PERHOUR.HOUR);

select BUSINESSES.BASE.CATEGORIES, sum(CT.BASE.CHECKINS)
from "CHECKINS_TABLE" as CT inner join BUSINESSES on CT.BUSINESSID = BUSINESS.pk 
where BUSINESSES.BASE.ISOPEN = 1 and (CT.PERHOUR.WEEKDAY = 'Mon' or CT.PERHOUR.WEEKDAY = 'Tue' or CT.PERHOUR.WEEKDAY = 'Wed' or CT.PERHOUR.WEEKDAY = 'Thu' or CT.PERHOUR.WEEKDAY = 'Fri') and CT.PERHOUR.HOUR > '13:59:00' and CT.PERHOUR.HOUR < '16:O1:00'
group by BUSINESSES.BASE.CATEGORIES;

drop table BUSINESSES;
drop table "CHECKINS_TABLE";


/*Q7*/
create table BUSINESSES (pk VARCHAR PRIMARY KEY, BASE.NAME VARCHAR, BASE.NEIGHBORHOOD VARCHAR, BASE.ADRRESS VARCHAR, BASE.CITY VARCHAR, BASE.STATE VARCHAR, BASE.POSTALCODE INT, BASE.LATITUDE INT, BASE.LONGTITUDE INT, BASE.STARS FLOAT, BASE.REVIEWCOUNT INT, BASE.ISOPEN INT, BASE.CATEGORIES VARCHAR)
as select "HBASE_ROW_KEY", BASE.NAME, BASE.NEIGHBORHOOD, BASE.ADRRESS, BASE.CITY, BASE.STATE, BASE.POSTALCODE, BASE.LATITUDE, BASE.LONGTITUDE, BASE.STARS, "BASE.REVIEW_COUNT", "BASE.IS_OPEN", BASE.CATEGORIES from "USER16.YELP_BUSINESS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create table CHECKINS_TABLE as CT (pk VARCHAR PRIMARY KEY, PERHOUR.BUSINESSID VARCHAR, PERHOUR.WEEKDAY VARCHAR, PERHOUR.CHECKINS INT) as select "HBASE_ROW_KEY", PERHOUR.BUSINESSID, PERHOUR.WEEKDAY, PERHOUR.CHECKINS from "USER16.YELP_CHECKINS" SALT_BUCKETS=16 COMPRESSION='GZ' IMMUTABLE_ROWS=true;

create index CIDX on "CHECKINS_TABLE"(PERHOUR.BUSINESSID, PERHOUR.WEEKDAY, PERHOUR.CHECKINS);

select B.pk as ID, B.BASE.NAME, B.BASE.NEIGHBORHOOD, B.BASE.ADRRESS, B.BASE.CITY, B.BASE.STATE, B.BASE.POSTALCODE, B.BASE.LATITUDE, B.BASE.LONGTITUDE, B.BASE.STARS, B.BASE.REVIEWCOUNT, B.BASE.ISOPEN, B.BASE.CATEGORIES
from BUSINESSES as B inner join "CHECKINS_TABLE" as CT on B.pk = CT.PERHOUR.BUSINESSID
where CT.PERHOUR.WEEKDAY = 'Sat'
group by B.pk
order by sum(CT.PERHOUR.CHECKINS) desc
limit 100;

drop table BUSINESSES;
drop table "CHECKINS_TABLE";



