create view USER16.YELP_BUSINESS (pk VARCHAR PRIMARY KEY, BASE.NAME VARCHAR, BASE.ADRRESS VARCHAR, BASE.CITY VARCHAR, BASE.REVIEWCOUNT VARCHAR, BASE.CATEGORIES VARCHAR);

select BASE.NAME, BASE.CITY, BASE.ADRRESS, BASE.REVIEWCOUNT
from USER16.YELP_BUSINESS
where BASE.CATEGORIES = 'Drugstores'
order by TO_NUMBER(BASE.REVIEWCOUNT) DESC;

drop view USER16.YELP_BUSINESS;




create view USER16.YELP_BUSINESS (pk VARCHAR PRIMARY KEY, BASE.NAME VARCHAR, BASE.ADRRESS VARCHAR, BASE.CITY VARCHAR, BASE.REVIEWCOUNT VARCHAR, BASE.CATEGORIES VARCHAR) SALT_BUCKETS=16, COMPRESSION='GZ', IMMUTABLE_ROWS=true;

create index BIDX on USER16.YELP_BUSINESS (BASE.NAME, BASE.ADRRESS, BASE.CITY, BASE.REVIEWCOUNT,BASE.CATEGORIES);

select BASE.NAME, BASE.CITY, BASE.ADRRESS, BASE.REVIEWCOUNT
from USER16.YELP_BUSINESS
where BASE.CATEGORIES = 'Drugstores'
order by TO_NUMBER(BASE.REVIEWCOUNT) DESC;

drop view USER16.YELP_BUSINESS;






