create table USER16.YELP_BUSINESS (pk VARCHAR PRIMARY KEY, BASE.REVIEWCOUNT VARCHAR, BASE.ISOPEN VARCHAR, BASE.CATEGORIES VARCHAR, BASE.STATE VARCHAR, ATTRIBUTES.SMOKING VARCHAR, HOURS.MONDAY VARCHAR, HOURS.TUESDAY VARCHAR, HOURS.WEDNESDAY VARCHAR, HOURS.THURSDAY VARCHAR, HOURS.FRIDAY VARCHAR, HOURS.SATURDAY VARCHAR, HOURS.SUNDAY VARCHAR);

select BASE.CATEGORIES, SUM(TO_NUMBER(BASE.REVIEWCOUNT)) as review_count
from USER16.YELP_BUSINESS
where BASE.ISOPEN = '1' AND HOURS.MONDAY = '0:0-0:0' AND HOURS.TUESDAY = '0:0-0:0' AND HOURS.WEDNESDAY = '0:0-0:0' AND HOURS.THURSDAY = '0:0-0:0' AND HOURS.FRIDAY = '0:0-0:0' AND HOURS.SATURDAY = '0:0-0:0' AND HOURS.SUNDAY = '0:0-0:0'
group by BASE.CATEGORIES;




create table USER16.YELP_BUSINESS (pk VARCHAR PRIMARY KEY, BASE.REVIEWCOUNT VARCHAR, BASE.ISOPEN VARCHAR, BASE.CATEGORIES VARCHAR, BASE.STATE VARCHAR, ATTRIBUTES.SMOKING VARCHAR, HOURS.MONDAY VARCHAR, HOURS.TUESDAY VARCHAR, HOURS.WEDNESDAY VARCHAR, HOURS.THURSDAY VARCHAR, HOURS.FRIDAY VARCHAR, HOURS.SATURDAY VARCHAR, HOURS.SUNDAY VARCHAR) SALT_BUCKETS=16, COMPRESSION='GZ', IMMUTABLE_ROWS=true;

create index BIDX3 on USER16.YELP_BUSINESS (BASE.REVIEWCOUNT, BASE.ISOPEN, BASE.CATEGORIES, HOURS.MONDAY, HOURS.TUESDAY, HOURS.WEDNESDAY, HOURS.THURSDAY, HOURS.FRIDAY, HOURS.SATURDAY, HOURS.SUNDAY);

select BASE.CATEGORIES, SUM(TO_NUMBER(BASE.REVIEWCOUNT)) as review_count
from USER16.YELP_BUSINESS
where BASE.ISOPEN = '1' AND HOURS.MONDAY = '0:0-0:0' AND HOURS.TUESDAY = '0:0-0:0' AND HOURS.WEDNESDAY = '0:0-0:0' AND HOURS.THURSDAY = '0:0-0:0' AND HOURS.FRIDAY = '0:0-0:0' AND HOURS.SATURDAY = '0:0-0:0' AND HOURS.SUNDAY = '0:0-0:0'
group by BASE.CATEGORIES;







