select BASE.STATE, COUNT(*)
from USER16.YELP_BUSINESS
where ATTRIBUTES.SMOKING = 'no' AND NOT HOURS.SUNDAY = 'None'
group by BASE.STATE;





create index BIDX4 on USER16.YELP_BUSINESS (BASE.STATE, ATTRIBUTES.SMOKING, HOURS.SUNDAY);

select BASE.STATE, COUNT(*)
from USER16.YELP_BUSINESS
where ATTRIBUTES.SMOKING = 'no' AND NOT HOURS.SUNDAY = 'None'
group by BASE.STATE;


alter table USER16.YELP_BUSINESS add ATTRIBUTES.SMOKING VARCHAR;









