create view USER16.YELP_CHECKIN (pk VARCHAR PRIMARY KEY, PERHOUR.CHECKINS VARCHAR, PERHOUR.WEEKDAY VARCHAR, PERHOUR.HOUR VARCHAR);

select PERHOUR.WEEKDAY, PERHOUR.HOUR, SUM(TO_NUMBER(PERHOUR.CHECKINS)) from USER16.YELP_CHECKIN where not PERHOUR.CHECKINS = 'checkins' group by PERHOUR.WEEKDAY, PERHOUR.HOUR;

drop view USER16.YELP_CHECKIN;





create view USER16.YELP_CHECKIN (pk VARCHAR PRIMARY KEY, PERHOUR.CHECKINS VARCHAR, PERHOUR.WEEKDAY VARCHAR, PERHOUR.HOUR VARCHAR) SALT_BUCKETS=16, COMPRESSION='GZ', IMMUTABLE_ROWS=true;

create index CIDX on USER16.YELP_CHECKIN(PERHOUR.CHECKINS, PERHOUR.WEEKDAY, PERHOUR.HOUR);

select PERHOUR.WEEKDAY, PERHOUR.HOUR, SUM(TO_NUMBER(PERHOUR.CHECKINS)) from USER16.YELP_CHECKIN where not PERHOUR.CHECKINS = 'checkins' group by PERHOUR.WEEKDAY, PERHOUR.HOUR;

drop view USER16.YELP_CHECKIN;


















